#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Amnesty.Resource", IsApplication=true)]

namespace Amnesty
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int TopLabelPersonal = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int btnChange = 2131099660;
			
			// aapt resource value: 0x7f06001b
			public const int btnConfirm = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int btnDonate = 2131099662;
			
			// aapt resource value: 0x7f060020
			public const int btnHome = 2131099680;
			
			// aapt resource value: 0x7f06000d
			public const int chkConfirm = 2131099661;
			
			// aapt resource value: 0x7f06001c
			public const int imageView1 = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int lblAmount = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int lblBankaccount = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int lblEmail = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int lblFirstname = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int lblLastname = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout1 = 2131099673;
			
			// aapt resource value: 0x7f06000f
			public const int scroll = 2131099663;
			
			// aapt resource value: 0x7f06001e
			public const int textView1 = 2131099678;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView4 = 2131099651;
			
			// aapt resource value: 0x7f060017
			public const int textView5 = 2131099671;
			
			// aapt resource value: 0x7f060008
			public const int textView6 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textView7 = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int textView8 = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int txtAmount = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int txtBankaccount = 2131099657;
			
			// aapt resource value: 0x7f06001f
			public const int txtDonatorEmail = 2131099679;
			
			// aapt resource value: 0x7f060004
			public const int txtEmail = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int txtFirstname = 2131099665;
			
			// aapt resource value: 0x7f06001a
			public const int txtFormError = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int txtLastname = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int txtName = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int txtPostalCode = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int txtStreetNr = 2131099654;
			
			// aapt resource value: 0x7f06001d
			public const int txtThanks = 2131099677;
			
			// aapt resource value: 0x7f060007
			public const int txtTown = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Confirmation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Form = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Thankyou = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int amount = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int bankaccount = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int birthdate = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int email = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int firstname = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lastname = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
